import Head from "next/head";
import Image from "next/image";
import PreviewCard from "../components/store-preview-card/preview-card";
import styles from "../styles/Home.module.css";
import { getCoffeePhotos, getCoffeeStores } from "../utils/coffee-stores";
import useGeoLocation from "../hooks/useGeoLocation";
import { useContext, } from "react";
import {
  CoffeeStoreContext,
  COFFEE_STORE_ACTION_TYPES,
} from "../contexts/coffee-store-context";

const FALLBACK_COFFEE_IMAGE =
  "https://images.pexels.com/photos/799869/pexels-photo-799869.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1";

export async function getStaticProps() {
  const [coffeeStores, coffeePhotos] = await Promise.all([
    getCoffeeStores(),
    getCoffeePhotos(),
  ]);

  return {
    props: {
      coffeeStores,
      coffeePhotos,
    },
  };
}

export default function Home(props) {
  // const [nearbyStores, setNearbyStores] = useState([]);
  const { dispatch, state } = useContext(CoffeeStoreContext);
  const { nearbyStores, nearbyPhotos, latlong } = state;
  // const [nearbyPhotos, setNearbyPhotos] = useState([]);
  const { getLocation, loading, locationError } = useGeoLocation();

  if (!props.coffeeStores.length) {
    return <p style={{ color: "white" }}>No stores to show</p>;
  }

  const handleGetLocation = async () => {
    getLocation();
    //get nearby shops, by latlong
    let nearbyStores = await fetch(`/api/coffeeStoresByLocation?latlong=${latlong}&limit=16`);
    nearbyStores = await nearbyStores.json();
    const nearbyPhotos = await getCoffeePhotos(16);
    dispatch({
      type: COFFEE_STORE_ACTION_TYPES.SET_COFFEE_STORES,
      payload: nearbyStores,
    });
    dispatch({
      type: COFFEE_STORE_ACTION_TYPES.SET_COFFEE_STORE_PHOTOS,
      payload: nearbyPhotos,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoissuer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.banner}>
          <div className={styles.bannerImg}>
            <Image src="/static/banner-img.jpg" layout="fill" />
          </div>
          <div className={styles.bannerText}>
            <h1>Coffee Connoissuer</h1>
            <p>Disover your local coffee shops</p>
            <button onClick={handleGetLocation}>
              {loading ? "Locating..." : "View shops nearby"}
            </button>
          </div>
        </div>

        {/* stores list */}
        {nearbyStores.length > 0 && (
          <div className={styles.storesWrapper}>
            <h2>Stores near you</h2>
            <div className={styles.storeGrid}>
              {nearbyStores.map((store, index) => (
                <PreviewCard
                  key={store.id}
                  id={store.id}
                  imgUrl={
                    nearbyPhotos[index]
                      ? nearbyPhotos[index].smallURL
                      : FALLBACK_COFFEE_IMAGE
                  }
                  title={store.name}
                />
              ))}
            </div>
          </div>
        )}

        {/* stores list */}
        <div className={styles.storesWrapper}>
          <h2>Explore Stores</h2>
          <div className={styles.storeGrid}>
            {props.coffeeStores.map((store, index) => (
              <PreviewCard
                key={store.id}
                id={store.id}
                imgUrl={
                  props.coffeePhotos[index]
                    ? props.coffeePhotos[index].smallURL
                    : FALLBACK_COFFEE_IMAGE
                }
                title={store.name}
              />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
